/*
	The sequence of triangle numbers is generated by adding the natural numbers.
	So the 7^(th) triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
	The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
	
	Let us list the factors of the first seven triangle numbers:
     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

	We can see that 28 is the first triangle number to have over five divisors.
	What is the value of the first triangle number to have over five hundred divisors?
*/

#include <iostream>
using namespace std;

int limit=500, i, triangle, divisors, percent;

int main(){
	while(divisors<=limit){
		i++; divisors=0;
		triangle = i*(i+1)/2;
		for (int j=1; j<=triangle/2; j++)
			if (triangle%j == 0) divisors++;

		if ((divisors*100)/limit > percent){
			percent = (divisors*100)/limit;
			printf("%3i%% %i\n", percent>100 ? 100:percent, divisors);
		}
	}
	printf("\nSolution: %i\n\n", triangle);

	system("pause");
	return 0;
}